name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      ecr_repository:
        description: 'ECR repository name'
        required: true
        default: 'umami'
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'
      aws_region:
        description: 'AWS region'
        required: true
        default: 'eu-west-2'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      TF_VAR_container_image: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/umami:latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Debug container image
        run: echo "Container image = $TF_VAR_container_image"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan