name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_container_image: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/umami:latest"
      TF_VAR_container_name: "${{ secrets.ECR_REPOSITORY }}"
      TF_VAR_container_port: "3000"
      AWS_REGION: "eu-west-2"
      TF_VAR_rds_db_name: "${{ secrets.RDS_DB_NAME }}"
      TF_VAR_rds_username: "${{ secrets.RDS_USERNAME }}"
      TF_VAR_rds_password: "${{ secrets.RDS_PASSWORD }}"
      TF_VAR_rds_port: "5432"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve